COLORS = {
    '#FF6B6B': 'Red', '#4ECDC4': 'Light Blue', '#FFE66D': 'Yellow',
    '#95A5A6': 'Gray', '#2ECC71': 'Green', '#E056FD': 'Purple',
    '#FF7F50': 'Orange', '#34495E': 'Dark Blue', '#F1C40F': 'Bright Yellow',
    '#8E44AD': 'Deep Purple', '#00B894': 'Dark Green', '#FD79A8': 'Pink',
    '#F39C12': 'Dark Orange', '#6C5CE7': 'Blue', '#A8E6CF': 'Light Green',
    '#FF9FF3': 'Light Pink', '#FFA07A': 'Pale Orange', '#45B7D1': 'Medium Blue',
    '#98FB98': 'Pale Green', '#DDA0DD': 'Light Purple', '#FF4757': 'Bright Red',
    '#2980B9': 'Medium Blue', '#FAD02E': 'Light Yellow', '#A3CB38': 'Medium Green',
    '#D980FA': 'Medium Purple', '#FF7043': 'Dark Red', '#48DBFB': 'Pale Blue',
    '#BADC58': 'Light Green', '#E84393': 'Dark Pink', '#574B90': 'Dark Purple',
    '#FF5252': 'Bright Red', '#00BCD4': 'Cyan', '#FFEB3B': 'Bright Yellow',
    '#607D8B': 'Blue Gray', '#4CAF50': 'Medium Green', '#9C27B0': 'Deep Purple',
    '#FF9800': 'Medium Orange', '#1E88E5': 'Bright Blue', '#FDD835': 'Medium Yellow',
    '#673AB7': 'Royal Purple', '#009688': 'Teal', '#E91E63': 'Medium Pink',
    '#FF5722': 'Deep Orange', '#3F51B5': 'Indigo', '#8BC34A': 'Pale Green',
    '#BA68C8': 'Medium Purple', '#FF8A65': 'Light Orange', '#03A9F4': 'Sky Blue',
    '#C0CA33': 'Olive Green', '#7E57C2': 'Light Purple'
}

BUTTON_LABELS = [
    'Submit', 'Cancel', 'Save', 'Delete', 'Update', 'Edit', 'Create', 'Add', 'Remove', 'Login',
    'Logout', 'Register', 'Sign Up', 'Sign In', 'Continue', 'Next', 'Previous', 'Back', 'Forward', 'Apply',
    'Reset', 'Clear', 'Search', 'Filter', 'Sort', 'Download', 'Upload', 'Export', 'Import', 'Print',
    'Share', 'Send', 'Receive', 'Accept', 'Decline', 'Approve', 'Reject', 'Confirm', 'Verify', 'Validate',
    'Close', 'Open', 'Start', 'Stop', 'Pause', 'Resume', 'Refresh', 'Reload', 'Retry', 'Skip',
    'Done', 'Finish', 'Complete', 'Begin', 'End', 'Help', 'Support', 'Settings', 'Options', 'Preferences',
    'Profile', 'Account', 'Menu', 'Home', 'Browse', 'View', 'Show', 'Hide', 'Expand', 'Collapse',
    'Maximize', 'Minimize', 'Zoom In', 'Zoom Out', 'Copy', 'Paste', 'Cut', 'Undo', 'Redo', 'Select',
    'Select All', 'Deselect', 'Check', 'Uncheck', 'Enable', 'Disable', 'Lock', 'Unlock', 'Block', 'Unblock',
    'Follow', 'Unfollow', 'Like', 'Unlike', 'Rate', 'Review', 'Comment', 'Reply', 'Post', 'Publish',
    'Draft', 'Archive', 'Restore', 'Backup', 'Sync', 'Connect', 'Disconnect', 'Link', 'Unlink', 'Merge',
    'Split', 'Group', 'Ungroup', 'Add to Cart', 'Checkout', 'Purchase', 'Buy Now', 'Pay', 'Subscribe', 'Unsubscribe',
    'Install', 'Uninstall', 'Update Now', 'Learn More', 'Get Started', 'Try Now', 'Preview', 'Launch', 'Run', 'Execute',
    'Generate', 'Calculate', 'Analyze', 'Compare', 'Match', 'Find', 'Replace', 'Track', 'Monitor', 'Schedule',
    'Plan', 'Organize', 'Customize', 'Configure', 'Setup', 'Initialize', 'Format', 'Convert', 'Transform', 'Upgrade',
    'Downgrade', 'Proceed', 'Join', 'Leave', 'Exit', 'Quit', 'Yes', 'No', 'Maybe', 'OK',
    'Cancel', 'Apply Changes', 'Save Changes', 'Discard Changes', 'Revert', 'Send Message', 'Read More', 'Show Less', 'Load More', 'See All',
    'Play', 'Pause', 'Fast Forward', 'Rewind', 'Shuffle', 'Repeat', 'Skip Intro', 'Turn On', 'Turn Off', 'Switch',
    'Toggle', 'Rotate', 'Flip', 'Move', 'Resize', 'Crop', 'Adjust', 'Optimize', 'Clean', 'Scan',
    'Verify Email', 'Reset Password', 'Change Password', 'Remember Me', 'Forgot Password', 'Get Help', 'Contact Us', 'Send Feedback', 'Report Issue', 'Got It'
]

ICONS = [
  "activity",
  "airplay",
  "alert-circle",
  "alert-octagon",
  "alert-triangle",
  "align-center",
  "align-justify",
  "align-left",
  "align-right",
  "anchor",
  "aperture",
  "archive",
  "arrow-down-circle",
  "arrow-down-left",
  "arrow-down-right",
  "arrow-down",
  "arrow-left-circle",
  "arrow-left",
  "arrow-right-circle",
  "arrow-right",
  "arrow-up-circle",
  "arrow-up-left",
  "arrow-up-right",
  "arrow-up",
  "at-sign",
  "award",
  "bar-chart",
  "battery-charging",
  "battery",
  "bell-off",
  "bell",
  "bluetooth",
  "bold",
  "book-open",
  "book",
  "bookmark",
  "box",
  "briefcase",
  "calendar",
  "camera-off",
  "camera",
  "cast",
  "check-circle",
  "check-square",
  "check",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "chevron-up",
  "chevrons-down",
  "chevrons-left",
  "chevrons-right",
  "chevrons-up",
  "chrome",
  "circle",
  "clipboard",
  "clock",
  "cloud-drizzle",
  "cloud-lightning",
  "cloud-off",
  "cloud-rain",
  "cloud-snow",
  "cloud",
  "code",
  "codepen",
  "codesandbox",
  "coffee",
  "columns",
  "command",
  "compass",
  "copy",
  "corner-down-left",
  "corner-down-right",
  "corner-left-down",
  "corner-left-up",
  "corner-right-down",
  "corner-right-up",
  "corner-up-left",
  "corner-up-right",
  "cpu",
  "credit-card",
  "crop",
  "crosshair",
  "database",
  "delete",
  "disc",
  "divide-circle",
  "divide-square",
  "divide",
  "dollar-sign",
  "download-cloud",
  "download",
  "dribbble",
  "droplet",
  "edit",
  "external-link",
  "eye-off",
  "eye",
  "facebook",
  "fast-forward",
  "feather",
  "figma",
  "file-minus",
  "file-plus",
  "file-text",
  "file",
  "film",
  "filter",
  "flag",
  "folder-minus",
  "folder-plus",
  "folder",
  "framer",
  "frown",
  "gift",
  "git-branch",
  "git-commit",
  "git-merge",
  "git-pull-request",
  "github",
  "gitlab",
  "globe",
  "grid",
  "hard-drive",
  "hash",
  "headphones",
  "heart",
  "help-circle",
  "hexagon",
  "home",
  "image",
  "inbox",
  "info",
  "instagram",
  "italic",
  "key",
  "layers",
  "layout",
  "life-buoy",
  "linkedin",
  "list",
  "loader",
  "lock",
  "log-in",
  "log-out",
  "mail",
  "map-pin",
  "map",
  "meh",
  "menu",
  "message-circle",
  "message-square",
  "mic-off",
  "mic",
  "minus-circle",
  "minus-square",
  "minus",
  "monitor",
  "moon",
  "more-horizontal",
  "more-vertical",
  "mouse-pointer",
  "move",
  "music",
  "navigation",
  "octagon",
  "package",
  "paperclip",
  "pause-circle",
  "pause",
  "pen-tool",
  "percent",
  "phone-call",
  "phone-forwarded",
  "phone-incoming",
  "phone-missed",
  "phone-off",
  "phone-outgoing",
  "phone",
  "pie-chart",
  "play-circle",
  "play",
  "plus-circle",
  "plus-square",
  "plus",
  "pocket",
  "power",
  "printer",
  "radio",
  "refresh-ccw",
  "refresh-cw",
  "repeat",
  "rewind",
  "rotate-ccw",
  "rotate-cw",
  "rss",
  "save",
  "scissors",
  "search",
  "send",
  "server",
  "settings",
  "shield-off",
  "shield",
  "shopping-bag",
  "shopping-cart",
  "shuffle",
  "sidebar",
  "skip-back",
  "skip-forward",
  "slack",
  "slash",
  "sliders",
  "smartphone",
  "smile",
  "speaker",
  "square",
  "star",
  "stop-circle",
  "sun",
  "sunrise",
  "sunset",
  "table",
  "tablet",
  "tag",
  "target",
  "terminal",
  "thermometer",
  "thumbs-down",
  "thumbs-up",
  "toggle-left",
  "toggle-right",
  "tool",
  "trash",
  "trello",
  "trending-down",
  "trending-up",
  "triangle",
  "truck",
  "tv",
  "twitch",
  "twitter",
  "type",
  "umbrella",
  "underline",
  "unlock",
  "upload-cloud",
  "upload",
  "user-check",
  "user-minus",
  "user-plus",
  "user",
  "users",
  "video-off",
  "video",
  "voicemail",
  "volume",
  "volume-x",
  "volume",
  "watch",
  "wifi-off",
  "wifi",
  "wind",
  "x-circle",
  "x-octagon",
  "x-square",
  "x",
  "youtube",
  "zap-off",
  "zap",
  "zoom-in",
  "zoom-out"
]