version: '3.8'
services:
  qwen2-vl:
    build: 
      context: ./services/qwen2-vl
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./services/qwen2-vl:/app 
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_LAUNCH_BLOCKING=1

  mask-generation:
    build: 
      context: ./services/mask-generation
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - MAX_CONCURRENT_TASKS=2
      - GPU_MEMORY_THRESHOLD=0.8

  workflow-engine:
    build:
      context: ./services/workflow-engine
      dockerfile: Dockerfile
    ports:
      - "9999:8080"
    depends_on:
      - mongo
      - mask-generation
      - qwen2-vl
    volumes:
      - ./services/workflow-engine:/app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: